version: '3.8'

networks:
  dev:
    driver: bridge

services:
  app-demo:
    build:
      context: ../
      dockerfile: Api/Dockerfile
    image: appdemo:latest
    container_name: appdemo-service
    ports:
      - "8080:80"
    depends_on:
      - app_db
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Host=app_db;Port=5432;Database=ToDoDev;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ToDoDev
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev

volumes:
  app_data:
